[providers]
providers = ['python']

[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[start]
cmd = 'cd backend && gunicorn app:app --bind 0.0.0.0:$PORT'
